const data = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tortor eros, congue non varius sed, aliquam vel augue. Vestibulum vel ligula congue, rutrum orci sit amet, eleifend felis. Cras facilisis libero mi, viverra lacinia orci vulputate sed. Curabitur maximus enim sit amet dolor imperdiet, vel ultrices nibh euismod. Aenean euismod tincidunt vehicula. Praesent molestie accumsan justo, eget faucibus nisi laoreet sed. Sed ut euismod justo. Suspendisse pharetra augue id ante vestibulum varius. Donec dictum augue vel fermentum rhoncus. Suspendisse non ex eget dolor vulputate blandit sed nec ex. Donec ac dui id massa placerat tincidunt ac blandit orci. Sed libero mi, malesuada eget risus at, blandit ultrices dolor. `,
  `Etiam ac tellus a mauris semper auctor quis et augue. Fusce sit amet tellus vel nulla condimentum convallis. Aliquam elementum accumsan molestie. Fusce ut tortor vel tortor sollicitudin ultricies. Vivamus mauris risus, commodo non luctus at, dapibus ut arcu. Vestibulum porttitor nunc euismod tellus finibus, vitae imperdiet mi efficitur. Fusce ultrices malesuada mi. Duis quis lacinia orci. Etiam gravida lorem in arcu posuere, vel pharetra nulla scelerisque. In tincidunt nisi neque, quis scelerisque dui euismod ultricies. Vivamus eu leo porta, vestibulum purus vitae, congue nisi. Donec quis felis ac elit suscipit blandit. Fusce interdum pellentesque mi. Aenean ornare, justo nec accumsan bibendum, urna arcu efficitur turpis, eget vehicula diam purus vitae massa. Curabitur egestas consequat sapien vitae ornare. `,
  `Mauris nisi risus, luctus vitae blandit a, tempor eget felis. Nam id consequat lorem. Nullam condimentum interdum odio, sit amet laoreet enim venenatis nec. Aliquam fermentum, diam eu maximus eleifend, purus mauris elementum nulla, at placerat lorem odio non tellus. Curabitur a pretium turpis. Morbi scelerisque quis est quis dictum. Morbi sit amet arcu nec massa pellentesque porta id faucibus sem. In hac habitasse platea dictumst. Vivamus vitae auctor nisi. Nullam tristique feugiat sagittis. Cras commodo aliquam neque, at malesuada nisl semper a.`,
  `Cras lacus velit, facilisis at nisl quis, auctor viverra elit. Sed dapibus sit amet ipsum quis accumsan. In in diam mauris. Donec velit eros, eleifend ac lorem id, finibus egestas ligula. Nunc eget leo gravida, interdum nisi et, viverra odio. Morbi dignissim elit a lacus convallis aliquet. Donec blandit nisi nec nulla lacinia, vel rhoncus tellus blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus congue augue ante, accumsan hendrerit diam viverra a. Praesent mollis justo ipsum, egestas vestibulum nibh ultrices a. Donec luctus ligula risus, a aliquam tellus egestas sit amet. Maecenas sodales orci ut mi gravida, non tempor augue vehicula. `,
  `Vestibulum quis lorem nibh. Curabitur suscipit est ac odio hendrerit gravida. Nunc interdum lacus est, a malesuada eros accumsan at. Nulla in lorem luctus, aliquet augue vel, posuere dui. Ut molestie lorem porta, consequat dolor vel, porta lorem. In hac habitasse platea dictumst. Nulla ullamcorper, erat ut porttitor viverra, augue purus efficitur neque, a ultricies mi dui ut nisi. `,
  `Fusce vel lacinia purus, sodales imperdiet tortor. Cras auctor vulputate augue. In sit amet posuere elit. Suspendisse potenti. Suspendisse potenti. Duis sit amet diam dictum erat vulputate blandit. Nunc fermentum purus eros, ut fringilla lectus gravida quis. `,
  `Pellentesque id vestibulum odio. Donec luctus risus at lorem lobortis, id bibendum diam mattis. Pellentesque scelerisque, nibh vitae accumsan ultricies, sem risus eleifend tellus, et tincidunt augue purus vel lectus. Nulla vitae faucibus justo. Etiam a nibh odio. Donec mauris nulla, porttitor vitae dolor sed, consequat tempus dolor. Donec nec pretium nunc. `,
];

export default data;
